### ISSUE TITLE
MHacks logo still wonky (height is messed up) when scrolling only.

### ISSUE THREAD

**Issue by TristanWiley** [mhacks/MHacks-Website#106]
Whenever loading the MHacks site from the default view (not scrolled at all) and then scrolling down the MHacks logo gets messed up (see screenshot)

![messedup](https://cloud.githubusercontent.com/assets/2747793/22749670/27693dc8-edfc-11e6-88e7-6ec424b9d4c8.JPG)

However whenever reloading the page after already scrolled partway on the page, the logo returns to normal.

**Comment by konnork** [comment]
Now that spring break is finally here, I can finally get to do things! Is this still an issue? I can't seem to reproduce

**Comment by TristanWiley** [comment]
Just checked, still an issue. Checking on my Dell XPS 15. If you load the page and scroll down it's stretched. But if you refresh the page after scrolling it looks fine.
