### ISSUE TITLE
Email button should not open new tab

### ISSUE THREAD

**Issue by abaileyb** [mhacks/MHacks-Website#11]
when clicking email in header as well as the sponsorship email address lower on the page, default mail client opens correctly and populates the To field, but it leaves the browser (Chrome windows 7) with a blank tab

**Comment by abaileyb** [comment]
@SigmanZero can you make it so the sponsorship email behaves this same way?

**Comment by SigmanZero** [comment]
Yes, good call. I'm going to reopen this issue so that I remember to do that xD
