### ISSUE TITLE
Make social media icons change on hover 

### ISSUE THREAD

**Issue by abaileyb** [mhacks/MHacks-Website#12]
Mentioned by Connor in #tech-frontend, just duplicating to github issues so that we have all in one place

**Comment by SigmanZero** [comment]
I made the tile with the icon change color, but to make the icon itself change color, I'll need a new version of the image with the different color. It's also worth mentioning that that might go against branding guidelines, but I'm not 100% sure about that. In any case, this can be revisited if need be.
