### ISSUE TITLE
Empty space when boxes are expanded

### ISSUE THREAD

**Issue by vrtiruko** [mhacks/MHacks-Website#14]
When the text boxes are expanded a lot of empty space is created at the bottom since the boxes currently only move down. Is there any way to have the boxes move to the side to minimize empty space? (Screenshots attached)
![screen shot 2016-08-10 at 5 49 07 pm](https://cloud.githubusercontent.com/assets/6538522/17573924/40b2fade-5f23-11e6-8a39-dd9cafd03114.png)
![screen shot 2016-08-10 at 5 49 28 pm](https://cloud.githubusercontent.com/assets/6538522/17573926/45683cba-5f23-11e6-90bd-e0c0d713ee16.png)

**Comment by SigmanZero** [comment]
Technically there's a way to rearrange all the tiles after expanding one so they fit nicely, but it gets tougher to guarantee that the tile you clicked stays in the relatively same spot. For now, I made the animation extend down. We can revisit this issue if it doesn't seem like a satisfactory fix.
