### ISSUE TITLE
Can't get to the application or log out

### ISSUE THREAD

**Issue by pvselvan** [mhacks/MHacks-Website#17]
<img width="1279" alt="screen shot 2016-08-11 at 9 52 28 am" src="https://cloud.githubusercontent.com/assets/10444861/17590841/636bc750-5fa9-11e6-9b6d-83b18013333f.png">

When I log in, it defaults to the dashboard, which is fine! We should probably put a message like "you can come back here for decisions and reminders, etc". 

But, when I click on the "apply" button in the top right corner, it doesn't go anywhere. It redirects back to the dashboard. Also, the "logout" button goes to a blank page.

**Comment by vrtiruko** [comment]
The log out button also doesn't work. If I go back to the home page and click "Apply" again, I'm still logged in.

**Comment by omkarmoghe** [comment]
fixed with ba86b25d0031be53be18137958c1bca1cc6d30f9 and 89ab71426cf76f8f612b5d4e7018e9cfe098fabc
