### ISSUE TITLE
CSS Refactor

### ISSUE THREAD

**Issue by manavgabhawala** [mhacks/MHacks-Website#2]
The CSS throughout the site needs to be refactored and made in a cleaner fashion. Inheritance should be used more appropriately. In general, I think a good goal to have for this MHacks is to factor out our style to the point where for the next MHacks style changes only require us to change the CSS and barely even think about the HTML. This would also require us to factor out all the "style" attributes from our HTML elements.

**Comment by omkarmoghe** [comment]
fixed in 3279e6b223d93162119c3f75aeaba59e820fd154, dd68241126042c4a07628794d3f5b9d54ee463a9, 5a543b688adb080ff654b0632f235132fd3f7e01? @manavgabhawala @michaelm244 pls confirm

**Comment by michaelm244** [comment]
yup I think that our CSS is pretty well structured now.
