### ISSUE TITLE
Title Bar does not resize correctly for mobile on 'Dashboard' page

### ISSUE THREAD

**Issue by abaileyb** [mhacks/MHacks-Website#20]
When browsing on an iPhone 6 plus, the 'apply' and 'logout' buttons are not visible when in portrait orientation. Here is a screenshot;
![img_1980](https://cloud.githubusercontent.com/assets/438881/17593938/6d911be8-5f9c-11e6-8439-527428e1f697.PNG)

**Comment by omkarmoghe** [comment]
fixed in one of @SigmanZero's dank commits
