### ISSUE TITLE
Masonic Temple / Date font different on dashboard page

### ISSUE THREAD

**Issue by abaileyb** [mhacks/MHacks-Website#21]
Home page:
![rightdatefont](https://cloud.githubusercontent.com/assets/438881/17600926/8ddd817a-5fba-11e6-8364-7a534b439f03.png)

Dashboard page:
![wrongdatefont](https://cloud.githubusercontent.com/assets/438881/17600927/8de048b0-5fba-11e6-80f0-545b2fc1ebd5.png)

**Comment by abaileyb** [comment]
not sure why the bottom screenshot came out so fuzzy but the idea is that headers should match

also buttons are round on dashboard now and square on homepage

**Comment by omkarmoghe** [comment]
fixed with 5a543b688adb080ff654b0632f235132fd3f7e01
