### ISSUE TITLE
[Low priority] 403 due to invalid csrf

### ISSUE THREAD

**Issue by anksh** [mhacks/MHacks-Website#23]
Open two tabs, one pointed to /login and one pointed to /register
Login with a valid account into the login tab.
Attempt to register on the second tab. Clicking submit causes a 403.

imo this is low priority since its a weird use case

**Comment by omkarmoghe** [comment]
yeah this is prob because it's trying to used the logged in session from one tab.. @manavgabhawala any thoughts?

**Comment by michaelm244** [comment]
this logic is handled by django, and i don't think it's the best use of our time to try to fix when our register confirmation page looks like this lol:
<img width="1440" alt="screen shot 2016-08-11 at 12 51 41 am" src="https://cloud.githubusercontent.com/assets/4361223/17655420/242f336c-627c-11e6-88f5-50c9622e827c.png">

**Comment by anksh** [comment]
Yeah agreed, I just wanted to make sure that this was known in case it was a symptom of something bigger
