### ISSUE TITLE
Post Registration Screen 

### ISSUE THREAD

**Issue by lbarwiko** [mhacks/MHacks-Website#24]
This page came up after I registered a new account.

![image](https://cloud.githubusercontent.com/assets/8712300/17626761/9d00e01c-607c-11e6-9d58-3b43b3a2286b.png)

Saw this issue twice with 2 different accounts.

**Comment by szechy** [comment]
I also saw this with three different accounts across Safari (9.1.2) and Chrome (52.0.2743.116) on OS X (10.11.6).

**Comment by omkarmoghe** [comment]
#16

**Comment by omkarmoghe** [comment]
fixed in fac35c506b9dc4400c62533532aa4e4d333e8583
