### ISSUE TITLE
"Applications coming soon!" runs into Email button

### ISSUE THREAD

**Issue by fishythefish** [mhacks/MHacks-Website#27]
When you scroll down the page, the header bar resizes. Depending on how quickly this happens, the text of "Applications coming soon!" can run into the Email button.

Unscrolled:
![scr1](https://cloud.githubusercontent.com/assets/187068/17641126/845b640a-60e1-11e6-9bf5-afcd0af13b62.png)

Scrolled:
![scr2](https://cloud.githubusercontent.com/assets/187068/17641127/845dbc14-60e1-11e6-9bce-0908fb60cb6a.png)

Also, if I scroll really fast, the "Applications coming soon!" never unwraps into a single line. (This doesn't cause spacing issues - it's just that the behavior is inconsistent.)

**Comment by omkarmoghe** [comment]
wontfix added since we are launching apps soon

**Comment by SigmanZero** [comment]
I actually fixed this in commit e3b4ce3cf4b3ac4563e40dd32b4ffe4925daed23 "Splash Page re-redesign" but didn't have a chance to update the issue
