### ISSUE TITLE
Expanding FAQ displaces boxes weirdly

### ISSUE THREAD

**Issue by fishythefish** [mhacks/MHacks-Website#28]
Because of the location and size of the FAQ box, expanding it causes other boxes to be placed weirdly.

Initial state:
![scr1](https://cloud.githubusercontent.com/assets/187068/17641157/59038958-60e2-11e6-9083-28c7372d0078.png)

(By the way, in the initial state, the right column of boxes is actually background - it looks weird that only these change color.)

Expanded:
![scr2](https://cloud.githubusercontent.com/assets/187068/17641149/1dc5bf64-60e2-11e6-8ac6-c3607ab44a57.png)

The FAQ box has now slid way over to the left, and suddenly there are stripes from the background because of the way only a handful of boxes slid straight down rather than filling into the spaces in the new rows.

Collapsed:
![scr3](https://cloud.githubusercontent.com/assets/187068/17641168/b7875bb2-60e2-11e6-8c43-3867cbd43a75.png)

FAQ box now remains left and the MLH box is weirdly hanging down.

**Comment by SigmanZero** [comment]
This isn't really relevant anymore since the FAQ box doesn't exist as of commit e3b4ce3cf4b3ac4563e40dd32b4ffe4925daed23 "Splash Page re-redesign," but regardless I've changed the way that packery rearranges the tiles so this would have been fixed even if we did still have the FAQ box.
