### ISSUE TITLE
"How much of the travel costs can you pay" should be a conditional question. 

### ISSUE THREAD

**Issue by pvselvan** [mhacks/MHacks-Website#39]
For travel reimbursements, “How much of the travel costs can you pay” should only appear after clicking the checkbox needing a travel reimbursement.

**Comment by abaileyb** [comment]
also I think for grammarz it should read "How much of the travel cost can you pay".

**Comment by abaileyb** [comment]
What would you think about adding the word 'dollars' after so it is clear that it's not a percentage or something. Like the answer to our question "How much of the travel cost can you pay" would be "__ dollars" not just a number.
