### ISSUE TITLE
Demographic info should be optional

### ISSUE THREAD

**Issue by vrtiruko** [mhacks/MHacks-Website#47]
Currently required to submit

**Comment by pkshultz** [comment]
![required](https://cloud.githubusercontent.com/assets/5421240/17686510/11d61bc6-633b-11e6-8986-2519989a1648.png)

**Comment by pkshultz** [comment]
In `MHacks-Website/MHacks/models.py`, [I think](http://stackoverflow.com/questions/16828315/how-can-i-make-my-model-fields-optional-in-django) a fix can be made by changing lines 163 and 164 from

```
gender = models.CharField(max_length=16, choices=GENDERS, default='none')
race = models.CharField(max_length=16, choices=RACES, default='none')
```

to

```
gender = models.CharField(max_length=16, choices=GENDERS, default='none', null=True, blank=True)
race = models.CharField(max_length=16, choices=RACES, default='none', null=True, blank=True)
```

I'd test it myself if I wasn't so lousy at setting up Postgres 🙃
