### ISSUE TITLE
Mobile home page

### ISSUE THREAD

**Issue by cgjohn** [mhacks/MHacks-Website#56]
![screenshot_20160816-212957](https://cloud.githubusercontent.com/assets/11685913/17718283/3fd98732-6413-11e6-9059-edc07e634a77.png)

on a galaxy s3 stock browser

**Comment by SigmanZero** [comment]
I'm not able to recreate this issue. I don't have an s3, so I've tried testing with various window sizes and used chrome's device mimicker, but the styling works fine. Any chance this is fixed by a cache clearing or page refresh? :P
