### ISSUE TITLE
Square box on registration confirmation

### ISSUE THREAD

**Issue by anksh** [mhacks/MHacks-Website#57]
<img width="1437" alt="screen shot 2016-08-16 at 6 27 14 pm" src="https://cloud.githubusercontent.com/assets/8533311/17722282/e242b4ea-63e5-11e6-97e7-852c5764cf52.png">
Theres a square at the end of the registration confirmation dialog. I'm using Chrome 52.0.2743.116 on OSX Yosemite

**Comment by abaileyb** [comment]
on windows 7 too

**Comment by omkarmoghe** [comment]
hmm gotta check the file encoding on this one. chrome usually supports emojis though

**Comment by omkarmoghe** [comment]
7ea0b16
