### ISSUE TITLE
FAQ Animations

### ISSUE THREAD

**Issue by omkarmoghe** [mhacks/MHacks-Website#64]
need `jQuery.fn.stop()` for the FAQ animations to prevent infinite cycling.

**Comment by michaelm244** [comment]
So I'm not sure exactly what you mean by infinite cycling, but I just sped up animation time. Let me know if it's still not fixed. Adding `jquery.fn.stop()` wasn't the solution in this case.

**Comment by SigmanZero** [comment]
Sorry I've been a bit mia, I know what the issue is - I'll take care of it as soon as i can get to a computer :)

**Comment by SigmanZero** [comment]
690684cd0aedf5f9bf9ac05255b65eb5a855f6d4
