### ISSUE TITLE
Make "Create an Account" more prominent on the page

### ISSUE THREAD

**Issue by tlaredo** [mhacks/MHacks-Website#9]
Put it in the Log In window

**Comment by omkarmoghe** [comment]
![image](https://cloud.githubusercontent.com/assets/4580292/17615509/98c42d46-6023-11e6-8981-3cddb577b7a3.png)

@tlaredo is this what you were talking about? It's part of that login block now.

**Comment by tlaredo** [comment]
@omkarmoghe yeah that looks way better
