### ISSUE TITLE
Hacker applications doesn't have mentor questions

### ISSUE THREAD

**Issue by yazadd** [mhacks/MHacks-Website#98]
Not sure how mentor applications work but I'm guessing when you answer yes to 'I am interested in mentoring other hackers!' a set of questions is supposed to pop up similar to those in the mentor application, and rn that doesn't happen

**Comment by SigmanZero** [comment]
Nah, we don't have any extra questions for Hackers who are also happy to Mentor, since their primary focus will be Hacking and they're there to help if they have time.
