### ISSUE TITLE
Can't Build on MacOS

### ISSUE THREAD

**Issue by jeffchang5** [mhacks/MHacks-Website#99]
`Command "/Users/jeffreychang/.virtualenvs/mhacks/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/32/bfx8rf_d20g5l8ff_d5cxbv40000gn/T/pip-build-7EYU6x/M2Crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/32/bfx8rf_d20g5l8ff_d5cxbv40000gn/T/pip-pSAFqP-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/jeffreychang/.virtualenvs/mhacks/bin/../include/site/python2.7/M2Crypto" failed with error code 1 in /private/var/folders/32/bfx8rf_d20g5l8ff_d5cxbv40000gn/T/pip-build-7EYU6x/M2Crypto/`

`pip install -r requirements.txt` fails on Sierra, using python 2.7

**Comment by SigmanZero** [comment]
Known issue and we're in the process of making it easier to install. For now you unfortunately just have to work through each error as it comes and install some things manually :P
